<?php

/**
 * Implementation of hook_menu().
 */
function simplegeo_map_menu() {
  return array(
    'admin/settings/simplegeo-map' => array(
      'title'           => 'Simplegeo Map Settings',
      'page callback'   => 'drupal_get_form',
      'page arguments'  => array('simplegeo_map_settings'),
      'access arguments'=> array('simplegeo map settings'),
      'description'     => 'Change settings for the simplegeo map',
      'file'            => 'simplegeo_map.admin.inc',
    ),
  );
}

/**
 * Implementation of hook_perm().
 */
function simplegeo_map_perm() {
  return array('simplegeo map settings');
}

/**
 * Gets the available marker themes.
 */
function simplegeo_map_marker_themes() {
  $sets = array();
  foreach (module_implements('simplegeo_map_marker_themes') as $module) {
    $res = call_user_func($module . '_simplegeo_map_marker_themes');
    if (is_array($res)) {
      $sets = $res + $sets;
    }
  }
  return $sets;
}

/**
 * Implementation of hook_simplegeo_map_marker_themes().
 */
function simplegeo_map_simplegeo_map_marker_themes() {
  global $base_path;

  $sets = array(
    'black' => array(
      'title' => t('Black'),
    ),
    'orange' => array(
      'title' => t('Orange'),
    ),
  );

  $url = $base_path . drupal_get_path('module', 'simplegeo_map') . '/img';

  $thresholds = array(
    array(
      'threshold' => 1,
      'size' => array(15, 21),
      'anchor' => array(8, 21),
    ),
    array(
      'threshold' => 2,
      'size' => array(21, 21),
      'anchor' => array(10, 10),
      'labelOffset' => array(-9, -5),
    ),
    array(
      'threshold' => 10,
      'size' => array(39, 39),
      'anchor' => array(19, 19),
      'labelOffset' => array(-19, -7),
    ),
    array(
      'threshold' => 50,
      'size' => array(49, 49),
      'anchor' => array(24, 24),
      'labelOffset' => array(-24, -10),
    ),
    array(
      'threshold' => 100,
      'size' => array(59, 59),
      'anchor' => array(24, 24),
      'labelOffset' => array(-24, -10),
    ),
  );

  foreach ($sets as $key => &$data) {
    foreach ($thresholds as $threshold) {
      $threshold['marker'] = $url . '/' . $key . '_' . $threshold['size'][0] . '.png';
      $data['markers'][] = $threshold;
    }
  }

  return $sets;
}

/**
 * Implementation of hook_block().
 */
function simplegeo_map_block($op = 'list', $delta = 0) {
  global $user;

  if ($op == 'list') {
    $block['map']['info'] = t('Map');
    return $block;
  }
  else if ($op == 'view') {
    if ($delta == 'map') {
      $position = variable_get('simple_geo_default_position', FALSE);
      $zoom = variable_get('simplegeo_map_default_zoom', 12);
      _simplegeo_map_setup_map($position, $zoom);

      $block['subject'] = t('Map');
      $block['content'] = '<div id="simplegeo-map-wrapper"><div id="simplegeo-map"></div></div>';
    }
  }
  return $block;
}

/**
 * Includes the necessary javascript and css files for the Simple Geo map.
 *
 * @param string $center
 * @param int $zoom
 * @return void
 */
function _simplegeo_map_setup_map($center = NULL, $zoom = NULL) {
  $path = drupal_get_path('module', 'simplegeo_map');
  drupal_add_js($path .'/js/simplegeo_map.js', 'module');
  drupal_add_js($path .'/js/jquery.cookie.js', 'module');

  $enabled_plugins = variable_get('simplegeo_map_plugins', array(
    'simplegeo_map_infowindow' => 'simplegeo_map_infowindow',
  ));

  foreach (module_implements('simplegeo_map_plugin') as $module) {
    $plugins = call_user_func($module . '_simplegeo_map_plugin');
    $module_path = drupal_get_path('module', $module);

    foreach ($plugins as $plugin) {
      if (empty($enabled_plugins[$plugin['name']])) {
        continue;
      }

      if (!empty($plugin['js'])) {
        foreach ($plugin['js'] as $script) {
          drupal_add_js($module_path . '/' . $script, 'module', 'footer');
        }
      }
      if (!empty($plugin['css'])) {
        foreach ($plugin['css'] as $css) {
          drupal_add_css($module_path . '/' . $css);
        }
      }
    }
  }

  // Add these JS files to the footer since they have to come after simplegeo_map.js
  // that loads the google maps api and because of aggregated CSS.
  drupal_add_js($path .'/js/labeledmarker.js', 'module', 'footer');
  drupal_add_js($path .'/js/ClusterMarker.js', 'module', 'footer');
  drupal_add_css($path .'/css/simplegeo_map.css');

  if ($center) {
    $settings['center'] = $center;
  }
  if ($zoom) {
    $settings['zoom'] = $zoom;
  }

  $settings['images'] = url(drupal_get_path('module', 'simplegeo_map') . '/img');
  $settings['maxNodes'] = variable_get('simplegeo_api_max_node_info', SIMPLEGEO_API_MAX_NODE_INFO);
  $settings['setUrlHash'] = variable_get('simplegeo_map_permalink_hash', FALSE);
  $themes = simplegeo_map_marker_themes();
  $theme = variable_get('simplegeo_map_marker_theme', 'orange');
  $settings['markerTheme'] = $themes[$theme];

  if (arg(0) == 'node' && is_numeric(arg(1))) {
    $node = node_load(arg(1));
    if (!empty($node->simple_geo_area)) {
      $settings['area'] = $node->simple_geo_area;
    }
  }

  // Allow other modules to alter our settings.
  drupal_alter('simplegeo_map_settings', $settings);
  drupal_add_js(array('simpleGeoMap' => $settings), 'setting');
}

/**
 * Implementation of hook_simplegeo_map_plugin().
 */
function simplegeo_map_simplegeo_map_plugin() {
  $plugins = array();

  $plugins[] = array(
    'name' => 'simplegeo_map_infowindow',
    'title' => t('Default info window'),
    'js' => array('js/simplegeo_infowindow.js'),
  );

  $plugins[] = array(
    'name' => 'simplegeo_map_microformat',
    'title' => t('Display microformat'),
    'js' => array('js/microformats.js'),
  );

  return $plugins;
}
